version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      composer-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /docker/wordpress
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /docker/wp-cli
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
